### ISSUE TITLE
Is there a way around underscore to camel case conversion?

### ISSUE THREAD

**Issue by howardroark** [cli-kit/cli-argparse#12]
Love the way you extract all the options without needing to pre-define them.  All other options seem to require definition.  I was wondering is there is any way around the underscore to camel case conversion?

Thanks!

**Comment by tmpfs** [comment]
Now there is :) In the registry as `1.0.11`, just set the `camelcase` option to `false`.

The rationale behind automatic conversion is that the convention for cli arguments is hyphenated whilst javascript properties are typically camelcase - I personally feel, `options['log-level']` to be somewhat more of a hassle than `options.logLevel`.

Thanks for the feedback, gave me a good nudge to tidy up some stuff too :)

Closing as implemented.

**Comment by tmpfs** [comment]
Ah, hold on, are you using cli arguments with underscores and they are being converted to camelcase?

**Comment by tmpfs** [comment]
Is it the case that you want hyphenated arguments converted to camelcase but to leave underscore variables alone?

**Comment by tmpfs** [comment]
I think it was a bad move me using an external library, I notice that the `camelcase` package also converts periods (`.`) I think I will go back to my original implementation of only converting to camelcase on hyphens. What do you think?

**Comment by tmpfs** [comment]
Ok, I thought it through a little more, see: 5a4f459afb3a90c137b6d118f07433c4e0a1a30e.

Test spec:

https://github.com/cli-kit/cli-argparse/blob/master/test/spec/camelcase.js

Docs:

https://github.com/cli-kit/cli-argparse#options

Should allow you to now handle option names as you please. Hope it helps.

Closing as re-implemented.

**Comment by tmpfs** [comment]
In the registry as `1.1.0` :)

**Comment by howardroark** [comment]
This is great! But not 100% what I am looking for, I should have been a little more specific. I am wanting to collect all options as a key+value store. What would be really great is for the ability to preserve all option names in the original format.

Do you have a special need for conversion?  Maybe allow for an option to enable, and disable?

Thanks!

**Comment by tmpfs** [comment]
Have you tried with the `camelcase` option set to `false`, that should do it.

> camelcase: When false do not convert option names to camelcase; when a string or regexp split the option name on the given pattern for conversion to camelcase.

Hope that does the job - let me know.

**Comment by tmpfs** [comment]
If it is the case that you want normal arguments *and* want to collect your key/value pairs, you should check out the `vars` option and result object, here you declare a convention such as `-D` or `@` for declaring variables that are put in the `vars` object of the result object. Note that when declaring variables in this way they must include the `=` sign.

See:

https://github.com/cli-kit/cli-argparse/blob/master/test/spec/vars.js

**Comment by howardroark** [comment]
I think `options` works best.  That setting did that trick.  Thanks!!
